错误的参数调用
FederatedAI/FATE-Flow pull request #259
Opened 2022-05-24 09:21 UTC by MiKKiYang

@dylan-fan @zhihuiwan 

修改文件：
python/fate_flow/utils/runtime_conf_parse_util.py
python/fate_flow/utils/schedule_utils.py

修改内容：
存在错误的参数调用

2022-05-25 02:58 UTC, MiKKiYang commented
@zhihuiwan @jat001 tks ~

2022-05-25 15:22 UTC, jat001 requested changes
DSLParserV1 is deprecated. just remove it

2022-05-26 01:42 UTC, MiKKiYang commented on python/fate_flow/utils/schedule_utils.py
>      elif isinstance(dsl_parser, DSLParserV1):
ok. i will kill that right now!

2022-05-26 02:07 UTC, jat001 approved these changes

2022-05-26 02:07 UTC, merged